stages:
   - build

before_script:
   - apt update
   - apt install build-essential cmake -qq -y
   - cmake .
   - make


build:ubuntu:
  image: ubuntu:latest
  stage: build
  script:
    - ./Release/swiftfetch

build:debian:
  image: debian:latest
  stage: build
  script:
    - ./Release/swiftfetch

build:alpine:
  image: alpine:latest
  stage: build
  script:
    - ./Release/swiftfetch
