stages:
   - build

before_script:
   - cmake .
   - make


build:ubuntu:
  image: gppcmake/ubuntu:7.4
  stage: build
  script:
    - ./Release/swiftfetch

build:debian:
  image: gppcmake/debian:8.3
  stage: build
  script:
    - ./Release/swiftfetch

build:alpine:
  image: gppcmake/alpine:8.3
  stage: build
  script:
    - ./Release/swiftfetch
